name: hotshop
description: "A hot shopping app project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  url_launcher: ^6.3.1
  auth0_flutter: ^1.7.2
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

#--------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ---------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/images/products/
    - assets/images/content/

  #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

# App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/t-store-splash-logo-black.png"
  adaptive_icon_background: "#764ba2"
  adaptive_icon_foreground: "assets/logos/t-store-splash-logo-white.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#764ba2"
  image: assets/logos/t-store-splash-logo-white.png
  web: false
  android_12:
    image: assets/logos/t-store-splash-logo-white.png
    color: "#764ba2"
  ios:
    image: assets/logos/t-store-splash-logo-white.png
    color: "#764ba2"
